version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: neuronos-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neuronos123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_transaction_timeout=60s
      - NEO4J_dbms_logs_query_enabled=INFO
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - neuronos-network
    restart: unless-stopped

  backend:
    build:
      context: ../../src/backend
      dockerfile: Dockerfile
    container_name: neuronos-backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neuronos123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=us-east-1-aws
    volumes:
      - ../../logs:/app/logs
      - ../../data:/app/data
      - /var/log/falco:/app/falco_logs:ro
    depends_on:
      - neo4j
    networks:
      - neuronos-network
    restart: unless-stopped

  frontend:
    build:
      context: ../../src/frontend
      dockerfile: Dockerfile
    container_name: neuronos-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - neuronos-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  neuronos-network:
    driver: bridge